version: "2.3"
services:
  kafka-metrics-processor:
    image: python:3.7-alpine
    container_name: kafka-metrics-processor
    cpus: 0.2
    restart: always

    volumes:
      - $PWD/Code/:/usr/src/app/:rw
      - $PWD/ELK/jmx_dashboard.json:/usr/src/app/jmx_dashboard.json:rw
    command: "bash -c 'pip install -r /usr/src/app/requirements.txt && cd /usr/src/app/ && python /usr/src/app/main.py'"
