version: "2.3"
services:
  kafkajmxexporter:
    image: abhiwalia/kafkajmxexporter
    container_name: kafkajmxexporter
    cpus: 0.2
    restart: always
    command: [ #Core JMX Metrics Gather Configurations
              "--jmx-zk-server","http://zookeeper:49900/",
              "--jmx-kafka-server","http://kafka1:49900/ ",
              "--jmx-kafka-server","http://kafka2:49900/ ",
              "--jmx-connect-server","http://connect:49900/ ",
              # Connect REST data ingestion
              "--enable-connect-rest-source",
              "--connect-rest-endpoint","https://connect:8083/ ",
              "--enable-connect-rest-auth",
              "--connect-rest-auth-user","superUser ",
              "--connect-rest-auth-pass","superUser ",
              # Enable ES Data Sink to Gather all the JMX data and stream it to Elastic
              "--enable-elastic-sink",
              "--es-url","http://elasticsearch:9200/ ",
              "--kibana-url","http://kibana:5601/ ",
              "--es-bulk-url-timeout","60 ",
              # Enable Kafka Data Sink to gather all the data and stream it to Kafka
              "--enable-kafka-sink",
              "--kafka-topic-name","jmx_data_ingestion_pipeline ",
              "--kafka-conn-props","bootstrap.servers=kafka1:12091 ",
              "--kafka-conn-props","client.id=JMX_Data_Producer ",
              "--kafka-conn-props","compression.type=snappy ",
              "--kafka-conn-props","retries=10 ",
              "--kafka-conn-props","linger.ms=50"
    ]
